# Generated by Django 3.0.3 on 2020-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_auto_20200229_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exp_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
